//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.LocalizedText", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altro ieri.
        /// </summary>
        internal static string AltroIeri {
            get {
                return ResourceManager.GetString("AltroIeri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avanti.
        /// </summary>
        internal static string Avanti {
            get {
                return ResourceManager.GetString("Avanti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ieri.
        /// </summary>
        internal static string Ieri {
            get {
                return ResourceManager.GetString("Ieri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indietro.
        /// </summary>
        internal static string Indietro {
            get {
                return ResourceManager.GetString("Indietro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inizia la ricerca.
        /// </summary>
        internal static string IniziaLaRicerca {
            get {
                return ResourceManager.GetString("IniziaLaRicerca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Con questa semplice procedura potrai ricercare le tue fotografie. Il nostro personale sarà a tua disposizione per ogni tua richiesta..
        /// </summary>
        internal static string LabelSpiagazioneHome {
            get {
                return ResourceManager.GetString("LabelSpiagazioneHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oggi.
        /// </summary>
        internal static string Oggi {
            get {
                return ResourceManager.GetString("Oggi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagina.
        /// </summary>
        internal static string Pagina {
            get {
                return ResourceManager.GetString("Pagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ricerca foto.
        /// </summary>
        internal static string RicercaFoto {
            get {
                return ResourceManager.GetString("RicercaFoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona un giorno dal calendario.
        /// </summary>
        internal static string SelezionaGiornoDalCalendario {
            get {
                return ResourceManager.GetString("SelezionaGiornoDalCalendario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ti ricordi il fotografo che ti ha scattato le foto, clicca sulla sua immagine. Se invece non te lo ricordi, prosegui oltre con il tasto &quot;&lt;i&gt;Avanti&lt;/i&gt;&quot;.
        /// </summary>
        internal static string Spiegazione2 {
            get {
                return ResourceManager.GetString("Spiegazione2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indica il giorno in cui è stata scattata la foto. Se non lo sai, o non te lo ricordi, prosegui oltre con il tasto &quot;&lt;i&gt;Avanti&lt;/i&gt;&quot;..
        /// </summary>
        internal static string Spiegazione3 {
            get {
                return ResourceManager.GetString("Spiegazione3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negozio di Fotografia - Ricerca Foto.
        /// </summary>
        internal static string TitoloBanner1 {
            get {
                return ResourceManager.GetString("TitoloBanner1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ricerca Foto - Imposta il Fotografo.
        /// </summary>
        internal static string TitoloBanner2 {
            get {
                return ResourceManager.GetString("TitoloBanner2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RicercaFoto - Imposta il Giorno.
        /// </summary>
        internal static string TitoloBanner3 {
            get {
                return ResourceManager.GetString("TitoloBanner3", resourceCulture);
            }
        }
    }
}
