//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Digiphoto.Lumen.OnRide.UI.FingerServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FingerServiceReference.IFingerprintService")]
    public interface IFingerprintService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFingerprintService/About", ReplyAction="http://tempuri.org/IFingerprintService/AboutResponse")]
        string About();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFingerprintService/About", ReplyAction="http://tempuri.org/IFingerprintService/AboutResponse")]
        System.Threading.Tasks.Task<string> AboutAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFingerprintService/GetNome", ReplyAction="http://tempuri.org/IFingerprintService/GetNomeResponse")]
        string GetNome(string template);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFingerprintService/GetNome", ReplyAction="http://tempuri.org/IFingerprintService/GetNomeResponse")]
        System.Threading.Tasks.Task<string> GetNomeAsync(string template);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFingerprintServiceChannel : Digiphoto.Lumen.OnRide.UI.FingerServiceReference.IFingerprintService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FingerprintServiceClient : System.ServiceModel.ClientBase<Digiphoto.Lumen.OnRide.UI.FingerServiceReference.IFingerprintService>, Digiphoto.Lumen.OnRide.UI.FingerServiceReference.IFingerprintService {
        
        public FingerprintServiceClient() {
        }
        
        public FingerprintServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FingerprintServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FingerprintServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FingerprintServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string About() {
            return base.Channel.About();
        }
        
        public System.Threading.Tasks.Task<string> AboutAsync() {
            return base.Channel.AboutAsync();
        }
        
        public string GetNome(string template) {
            return base.Channel.GetNome(template);
        }
        
        public System.Threading.Tasks.Task<string> GetNomeAsync(string template) {
            return base.Channel.GetNomeAsync(template);
        }
    }
}
