-- MySQL Script generated by MySQL Workbench
-- Wed Feb 13 20:51:17 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema lumen
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lumen
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lumen` DEFAULT CHARACTER SET utf8 ;
USE `lumen` ;

-- -----------------------------------------------------
-- Table `lumen`.`InfosFisse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lumen`.`InfosFisse` (
  `id` CHAR(1) NOT NULL,
  `ultimoNumFotogramma` INT(11) NOT NULL,
  `dataUltimoScarico` DATE NULL,
  `versioneDbCompatibile` VARCHAR(10) NOT NULL DEFAULT '4',
  `modoNumerazFoto` CHAR(1) NOT NULL DEFAULT 'M',
  `pixelProvino` SMALLINT(5) NOT NULL,
  `idPuntoVendita` VARCHAR(5) NULL,
  `descrizPuntoVendita` VARCHAR(50) NULL,
  `numGiorniEliminaFoto` SMALLINT(5) NOT NULL DEFAULT 0,
  `varie` VARCHAR(200) NULL,
  `urlPrefixSelfServiceWeb` VARCHAR(45) NULL,
  `scannerImpronte` varchar(20) null,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lumen`.`Fotografi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lumen`.`Fotografi` (
  `id` VARCHAR(16) NOT NULL,
  `cognomeNome` VARCHAR(50) NOT NULL,
  `iniziali` VARCHAR(2) NOT NULL,
  `attivo` BIT(1) NOT NULL DEFAULT 1,
  `umano` BIT(1) NOT NULL DEFAULT 1,
  `note` TEXT(500) NULL,
  `immagine` BLOB NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lumen`.`Prodotti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lumen`.`Prodotti` (
  `id` CHAR(36) NOT NULL,
  `Discriminator` VARCHAR(30) NOT NULL,
  `descrizione` VARCHAR(50) NOT NULL,
  `prezzo` DECIMAL(6,2) NOT NULL,
  `attivo` BIT(1) NOT NULL DEFAULT 1,
  `ordinamento` SMALLINT(5) NULL,
  `tipologia` CHAR(1) NOT NULL COMMENT '\'S=Stampa ; F=File\'',
  `st_grandezza` CHAR(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '			';


-- -----------------------------------------------------
-- Table `lumen`.`AzioniAutomatiche`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lumen`.`AzioniAutomatiche` (
  `id` CHAR(36) NOT NULL,
  `nome` VARCHAR(30) NOT NULL,
  `correzioniXml` TEXT NOT NULL,
  `attivo` BIT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lumen`.`Eventi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lumen`.`Eventi` (
  `id` CHAR(36) NOT NULL,
  `descrizione` VARCHAR(50) NOT NULL,
  `attivo` BIT(1) NOT NULL DEFAULT 1,
  `ordinamento` SMALLINT(5) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lumen`.`Fotografie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lumen`.`Fotografie` (
  `id` CHAR(36) NOT NULL,
  `nomeFile` VARCHAR(200) NOT NULL,
  `dataOraScatto` DATETIME NULL,
  `didascalia` VARCHAR(100) NULL,
  `dataOraAcquisizione` DATETIME NOT NULL,
  `numero` INT(11) NOT NULL,
  `faseDelGiorno` SMALLINT(1) NULL,
  `giornata` DATE NOT NULL,
  `correzioniXml` TEXT NULL,
  `contaStampata` SMALLINT(2) NOT NULL DEFAULT 0,
  `contaMasterizzata` SMALLINT(2) NOT NULL DEFAULT 0,
  `miPiace` BIT(1) NULL,
  `evento_id` CHAR(36) NULL,
  `fotografo_id` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Fotografie_Eventi_idx` (`evento_id` ASC),
  INDEX `fk_Fotografie_Fotografi1_idx` (`fotografo_id` ASC),
  INDEX `idx_fotografie_dataOraAcquisizione` (`dataOraAcquisizione` DESC),
  INDEX `idx_fotografie_giornata` (`giornata` ASC),
  INDEX `idx_fotografie_didascalia` (`didascalia` ASC),
  CONSTRAINT `fk_Fotografie_Eventi`
    FOREIGN KEY (`evento_id`)
    REFERENCES `lumen`.`Eventi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fotografie_Fotografi`
    FOREIGN KEY (`fotografo_id`)
    REFERENCES `lumen`.`Fotografi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lumen`.`ConsumiCartaGiornalieri`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lumen`.`ConsumiCartaGiornalieri` (
  `id` CHAR(36) NOT NULL,
  `giornata` DATE NOT NULL,
  `totFogli` SMALLINT(4) NOT NULL,
  `diCuiProvini` SMALLINT(4) NOT NULL,
  `diCuiFoto` SMALLINT(4) NOT NULL,
  `formatoCarta_id` CHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ConsumiCartaGiornalieri_FormatiCarta1_idx` (`formatoCarta_id` ASC),
  CONSTRAINT `fk_ConsumiCartaGiornalieri_FormatiCarta1`
    FOREIGN KEY (`formatoCarta_id`)
    REFERENCES `lumen`.`Prodotti` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lumen`.`ScarichiCards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lumen`.`ScarichiCards` (
  `id` CHAR(36) NOT NULL,
  `tempo` DATETIME NOT NULL,
  `totFoto` SMALLINT(5) NOT NULL,
  `giornata` DATE NOT NULL,
  `fotografo_id` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ScarichiCards_Fotografi1_idx` (`fotografo_id` ASC),
  CONSTRAINT `fk_ScarichiCards_Fotografi1`
    FOREIGN KEY (`fotografo_id`)
    REFERENCES `lumen`.`Fotografi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lumen`.`Giornate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lumen`.`Giornate` (
  `id` DATE NOT NULL,
  `orologio` DATETIME NOT NULL,
  `incassoDichiarato` DECIMAL(7,2) NOT NULL,
  `note` TEXT NULL,
  `incassoPrevisto` DECIMAL(7,2) NOT NULL,
  `prgTaglierina1` VARCHAR(20) NULL,
  `prgTaglierina2` VARCHAR(20) NULL,
  `prgTaglierina3` VARCHAR(20) NULL,
  `totScarti` SMALLINT(4) NULL,
  `firma` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lumen`.`Carrelli`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lumen`.`Carrelli` (
  `id` CHAR(36) NOT NULL,
  `giornata` DATE NOT NULL,
  `tempo` DATETIME NOT NULL,
  `totaleAPagare` DECIMAL(6,2) NULL,
  `intestazione` VARCHAR(100) NULL,
  `venduto` BIT(1) NOT NULL DEFAULT 0,
  `note` TEXT NULL,
  `totMasterizzate` SMALLINT(5) NOT NULL DEFAULT 0,
  `prezzoDischetto` DECIMAL(6,2) NULL,
  `visibileSelfService` BIT(1) NULL DEFAULT 1,
  `idCortoSelfService` CHAR(4) NULL,
  `applicatePromozioni` BIT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idCortoSelf_UNQ` (`idCortoSelfService` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lumen`.`RigheCarrelli`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lumen`.`RigheCarrelli` (
  `id` CHAR(36) NOT NULL,
  `prodotto_id` CHAR(36) NOT NULL,
  `prezzoLordoUnitario` DECIMAL(6,2) NOT NULL,
  `quantita` SMALLINT(3) NOT NULL,
  `prezzoNettoTotale` DECIMAL(6,2) NOT NULL,
  `sconto` DECIMAL(6,2) NULL,
  `descrizione` VARCHAR(100) NOT NULL,
  `discriminator` CHAR(1) NOT NULL,
  `totFogliStampati` SMALLINT(3) NULL,
  `nomeStampante` VARCHAR(255) NULL,
  `bordiBianchi` BIT(1) NULL,
  `carrello_id` CHAR(36) NOT NULL,
  `fotografo_id` VARCHAR(16) NOT NULL,
  `fotografia_id` CHAR(36) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_RigheCarrelli_Carrelli1_idx` (`carrello_id` ASC),
  INDEX `fk_RigheCarrelli_Fotografi1_idx` (`fotografo_id` ASC),
  INDEX `fk_RigheCarrelli_Fotografie1_idx` (`fotografia_id` ASC),
  INDEX `fk_RigheCarrelli_Prodotti1_idx` (`prodotto_id` ASC),
  CONSTRAINT `fk_RigheCarrelli_Carrelli1`
    FOREIGN KEY (`carrello_id`)
    REFERENCES `lumen`.`Carrelli` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RigheCarrelli_Fotografi1`
    FOREIGN KEY (`fotografo_id`)
    REFERENCES `lumen`.`Fotografi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RigheCarrelli_Fotografie1`
    FOREIGN KEY (`fotografia_id`)
    REFERENCES `lumen`.`Fotografie` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RigheCarrelli_Prodotti1`
    FOREIGN KEY (`prodotto_id`)
    REFERENCES `lumen`.`Prodotti` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lumen`.`IncassiFotografi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lumen`.`IncassiFotografi` (
  `id` CHAR(36) NOT NULL,
  `incasso` DECIMAL(6,2) NOT NULL,
  `incassoStampe` DECIMAL(6,2) NOT NULL,
  `incassoMasterizzate` DECIMAL(6,2) NOT NULL,
  `contaStampe` SMALLINT(5) NOT NULL,
  `contaMasterizzate` SMALLINT(5) NOT NULL,
  `provvigioni` DECIMAL(6,2) NULL,
  `carrello_id` CHAR(36) NOT NULL,
  `fotografo_id` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_IncassiFotografi_Carrelli1_idx` (`carrello_id` ASC),
  INDEX `fk_IncassiFotografi_Fotografi1_idx` (`fotografo_id` ASC),
  CONSTRAINT `fk_IncassiFotografi_Carrelli1`
    FOREIGN KEY (`carrello_id`)
    REFERENCES `lumen`.`Carrelli` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_IncassiFotografi_Fotografi1`
    FOREIGN KEY (`fotografo_id`)
    REFERENCES `lumen`.`Fotografi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lumen`.`Promozioni`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lumen`.`Promozioni` (
  `id` SMALLINT(2) NOT NULL,
  `descrizione` VARCHAR(50) NOT NULL,
  `Discriminator` VARCHAR(255) NOT NULL COMMENT 'La classe reale che istanzia questa Promo\n(polimorfismo gestito manualmente)',
  `attiva` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Se non è attiva non viene applicata',
  `esclusiva` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Se applico questa promozione, non ne applico più altre.\nFa fede il campo: priorità',
  `discrezionale` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'indica se obbligatoria oppure a discrezione dell\'utente.',
  `attivaSuStampe` TINYINT(1) NOT NULL DEFAULT 1,
  `attivaSuFile` TINYINT(1) NOT NULL DEFAULT 1,
  `priorita` TINYINT(2) NOT NULL DEFAULT 5,
  `prezzoFile` TINYINT(2) NULL,
  `qtaDaPrendere` TINYINT(3) NULL,
  `qtaDaPagare` TINYINT(3) NULL,
  `prodottoInnesco_id` CHAR(36) NULL,
  `qtaInnesco` TINYINT(3) NULL,
  `prodottoElargito_id` CHAR(36) NULL,
  `qtaElargito` TINYINT(3) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Promozioni_Prodotti1_idx` (`prodottoInnesco_id` ASC),
  INDEX `fk_Promozioni_Prodotti2_idx` (`prodottoElargito_id` ASC),
  CONSTRAINT `fk_Promozioni_Prodotti1`
    FOREIGN KEY (`prodottoInnesco_id`)
    REFERENCES `lumen`.`Prodotti` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Promozioni_Prodotti2`
    FOREIGN KEY (`prodottoElargito_id`)
    REFERENCES `lumen`.`Prodotti` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `lumen`.`Ospiti` (
  `id` INT(11) NOT NULL,
  `nome` VARCHAR(50) NULL DEFAULT NULL,
  `impronta` BLOB NOT NULL,
  ora DATETIME not null default CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
