//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Digiphoto.Lumen.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cartellaFoto {
            get {
                return ((string)(this["cartellaFoto"]));
            }
            set {
                this["cartellaFoto"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("05:30")]
        public string oraCambioGiornata {
            get {
                return ((string)(this["oraCambioGiornata"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*.jpg;*.jpeg;*.png;*.tif;*.tiff")]
        public string estensioniGrafiche {
            get {
                return ((string)(this["estensioniGrafiche"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int pixelLatoProvino {
            get {
                return ((int)(this["pixelLatoProvino"]));
            }
            set {
                this["pixelLatoProvino"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public short modoVendita {
            get {
                return ((short)(this["modoVendita"]));
            }
            set {
                this["modoVendita"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%PROGRAMDATA%\\digiPHOTO\\Lumen")]
        public string dbCartella {
            get {
                return ((string)(this["dbCartella"]));
            }
            set {
                this["dbCartella"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string descrizionePuntoVendita {
            get {
                return ((string)(this["descrizionePuntoVendita"]));
            }
            set {
                this["descrizionePuntoVendita"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string defaultMasterizzatore {
            get {
                return ((string)(this["defaultMasterizzatore"]));
            }
            set {
                this["defaultMasterizzatore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string defaultChiavetta {
            get {
                return ((string)(this["defaultChiavetta"]));
            }
            set {
                this["defaultChiavetta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool eraseFotoMemoryCard {
            get {
                return ((bool)(this["eraseFotoMemoryCard"]));
            }
            set {
                this["eraseFotoMemoryCard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pswAdmin {
            get {
                return ((string)(this["pswAdmin"]));
            }
            set {
                this["pswAdmin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string stampigli {
            get {
                return ((string)(this["stampigli"]));
            }
            set {
                this["stampigli"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cod")]
        public string codicePuntoVendita {
            get {
                return ((string)(this["codicePuntoVendita"]));
            }
            set {
                this["codicePuntoVendita"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string proiettaDiapo {
            get {
                return ((string)(this["proiettaDiapo"]));
            }
            set {
                this["proiettaDiapo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string destMasterizza {
            get {
                return ((string)(this["destMasterizza"]));
            }
            set {
                this["destMasterizza"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool autoZoomNoBordiBianchi {
            get {
                return ((bool)(this["autoZoomNoBordiBianchi"]));
            }
            set {
                this["autoZoomNoBordiBianchi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool primoAvvioLumen {
            get {
                return ((bool)(this["primoAvvioLumen"]));
            }
            set {
                this["primoAvvioLumen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string connectionString {
            get {
                return ((string)(this["connectionString"]));
            }
            set {
                this["connectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool primoAvvioConfiguratore {
            get {
                return ((bool)(this["primoAvvioConfiguratore"]));
            }
            set {
                this["primoAvvioConfiguratore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbvuoto.sdf")]
        public string dbNomeDbVuoto {
            get {
                return ((string)(this["dbNomeDbVuoto"]));
            }
            set {
                this["dbNomeDbVuoto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("database.sdf")]
        public string dbNomeDbPieno {
            get {
                return ((string)(this["dbNomeDbPieno"]));
            }
            set {
                this["dbNomeDbPieno"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public short giorniDeleteFoto {
            get {
                return ((short)(this["giorniDeleteFoto"]));
            }
            set {
                this["giorniDeleteFoto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string stampantiAbbinate {
            get {
                return ((string)(this["stampantiAbbinate"]));
            }
            set {
                this["stampantiAbbinate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isWindowPubblicaVisibile {
            get {
                return ((bool)(this["isWindowPubblicaVisibile"]));
            }
            set {
                this["isWindowPubblicaVisibile"] = value;
            }
        }
    }
}
