//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Digiphoto.Lumen.SelfService.MobileUI.SelfServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CarrelloDto", Namespace="http://schemas.datacontract.org/2004/07/Digiphoto.Lumen.SelfService.Carrelli")]
    [System.SerializableAttribute()]
    public partial class CarrelloDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titoloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string titolo {
            get {
                return this.titoloField;
            }
            set {
                if ((object.ReferenceEquals(this.titoloField, value) != true)) {
                    this.titoloField = value;
                    this.RaisePropertyChanged("titolo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FotografiaDto", Namespace="http://schemas.datacontract.org/2004/07/Digiphoto.Lumen.SelfService.Carrelli")]
    [System.SerializableAttribute()]
    public partial class FotografiaDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> miPiaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numeroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> miPiace {
            get {
                return this.miPiaceField;
            }
            set {
                if ((this.miPiaceField.Equals(value) != true)) {
                    this.miPiaceField = value;
                    this.RaisePropertyChanged("miPiace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroField, value) != true)) {
                    this.numeroField = value;
                    this.RaisePropertyChanged("numero");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SelfServiceReference.ISelfService")]
    public interface ISelfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISelfService/getListaCarrelli", ReplyAction="http://tempuri.org/ISelfService/getListaCarrelliResponse")]
        Digiphoto.Lumen.SelfService.MobileUI.SelfServiceReference.CarrelloDto[] getListaCarrelli();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISelfService/getListaCarrelli", ReplyAction="http://tempuri.org/ISelfService/getListaCarrelliResponse")]
        System.Threading.Tasks.Task<Digiphoto.Lumen.SelfService.MobileUI.SelfServiceReference.CarrelloDto[]> getListaCarrelliAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISelfService/getListaFotografie", ReplyAction="http://tempuri.org/ISelfService/getListaFotografieResponse")]
        Digiphoto.Lumen.SelfService.MobileUI.SelfServiceReference.FotografiaDto[] getListaFotografie(System.Guid carrelloId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISelfService/getListaFotografie", ReplyAction="http://tempuri.org/ISelfService/getListaFotografieResponse")]
        System.Threading.Tasks.Task<Digiphoto.Lumen.SelfService.MobileUI.SelfServiceReference.FotografiaDto[]> getListaFotografieAsync(System.Guid carrelloId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISelfService/getImage", ReplyAction="http://tempuri.org/ISelfService/getImageResponse")]
        byte[] getImage(System.Guid fotografiaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISelfService/getImage", ReplyAction="http://tempuri.org/ISelfService/getImageResponse")]
        System.Threading.Tasks.Task<byte[]> getImageAsync(System.Guid fotografiaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISelfService/setMiPiace", ReplyAction="http://tempuri.org/ISelfService/setMiPiaceResponse")]
        void setMiPiace(System.Guid fotografiaId, bool miPiace);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISelfService/setMiPiace", ReplyAction="http://tempuri.org/ISelfService/setMiPiaceResponse")]
        System.Threading.Tasks.Task setMiPiaceAsync(System.Guid fotografiaId, bool miPiace);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISelfServiceChannel : Digiphoto.Lumen.SelfService.MobileUI.SelfServiceReference.ISelfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SelfServiceClient : System.ServiceModel.ClientBase<Digiphoto.Lumen.SelfService.MobileUI.SelfServiceReference.ISelfService>, Digiphoto.Lumen.SelfService.MobileUI.SelfServiceReference.ISelfService {
        
        public SelfServiceClient() {
        }
        
        public SelfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SelfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SelfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SelfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Digiphoto.Lumen.SelfService.MobileUI.SelfServiceReference.CarrelloDto[] getListaCarrelli() {
            return base.Channel.getListaCarrelli();
        }
        
        public System.Threading.Tasks.Task<Digiphoto.Lumen.SelfService.MobileUI.SelfServiceReference.CarrelloDto[]> getListaCarrelliAsync() {
            return base.Channel.getListaCarrelliAsync();
        }
        
        public Digiphoto.Lumen.SelfService.MobileUI.SelfServiceReference.FotografiaDto[] getListaFotografie(System.Guid carrelloId) {
            return base.Channel.getListaFotografie(carrelloId);
        }
        
        public System.Threading.Tasks.Task<Digiphoto.Lumen.SelfService.MobileUI.SelfServiceReference.FotografiaDto[]> getListaFotografieAsync(System.Guid carrelloId) {
            return base.Channel.getListaFotografieAsync(carrelloId);
        }
        
        public byte[] getImage(System.Guid fotografiaId) {
            return base.Channel.getImage(fotografiaId);
        }
        
        public System.Threading.Tasks.Task<byte[]> getImageAsync(System.Guid fotografiaId) {
            return base.Channel.getImageAsync(fotografiaId);
        }
        
        public void setMiPiace(System.Guid fotografiaId, bool miPiace) {
            base.Channel.setMiPiace(fotografiaId, miPiace);
        }
        
        public System.Threading.Tasks.Task setMiPiaceAsync(System.Guid fotografiaId, bool miPiace) {
            return base.Channel.setMiPiaceAsync(fotografiaId, miPiace);
        }
    }
}
