//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Digiphoto.Lumen.Core.SpoolerServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SpoolerServiceReference.ISpoolerService")]
    public interface ISpoolerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISpoolerService/About", ReplyAction="http://tempuri.org/ISpoolerService/AboutResponse")]
        string About();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISpoolerService/About", ReplyAction="http://tempuri.org/ISpoolerService/AboutResponse")]
        System.Threading.Tasks.Task<string> AboutAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISpoolerService/EseguireStampe", ReplyAction="http://tempuri.org/ISpoolerService/EseguireStampeResponse")]
        void EseguireStampe(char td, System.Guid guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISpoolerService/EseguireStampe", ReplyAction="http://tempuri.org/ISpoolerService/EseguireStampeResponse")]
        System.Threading.Tasks.Task EseguireStampeAsync(char td, System.Guid guid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISpoolerServiceChannel : Digiphoto.Lumen.Core.SpoolerServiceReference.ISpoolerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SpoolerServiceClient : System.ServiceModel.ClientBase<Digiphoto.Lumen.Core.SpoolerServiceReference.ISpoolerService>, Digiphoto.Lumen.Core.SpoolerServiceReference.ISpoolerService {
        
        public SpoolerServiceClient() {
        }
        
        public SpoolerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SpoolerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SpoolerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SpoolerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string About() {
            return base.Channel.About();
        }
        
        public System.Threading.Tasks.Task<string> AboutAsync() {
            return base.Channel.AboutAsync();
        }
        
        public void EseguireStampe(char td, System.Guid guid) {
            base.Channel.EseguireStampe(td, guid);
        }
        
        public System.Threading.Tasks.Task EseguireStampeAsync(char td, System.Guid guid) {
            return base.Channel.EseguireStampeAsync(td, guid);
        }
    }
}
