//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace FormsTestApplication
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class test3Entities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new test3Entities1 object using the connection string found in the 'test3Entities1' section of the application configuration file.
        /// </summary>
        public test3Entities1() : base("name=test3Entities1", "test3Entities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new test3Entities1 object.
        /// </summary>
        public test3Entities1(string connectionString) : base(connectionString, "test3Entities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new test3Entities1 object.
        /// </summary>
        public test3Entities1(EntityConnection connection) : base(connection, "test3Entities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Articoli> Articoli
        {
            get
            {
                if ((_Articoli == null))
                {
                    _Articoli = base.CreateObjectSet<Articoli>("Articoli");
                }
                return _Articoli;
            }
        }
        private ObjectSet<Articoli> _Articoli;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Clienti> Clienti
        {
            get
            {
                if ((_Clienti == null))
                {
                    _Clienti = base.CreateObjectSet<Clienti>("Clienti");
                }
                return _Clienti;
            }
        }
        private ObjectSet<Clienti> _Clienti;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Vendita> Vendita
        {
            get
            {
                if ((_Vendita == null))
                {
                    _Vendita = base.CreateObjectSet<Vendita>("Vendita");
                }
                return _Vendita;
            }
        }
        private ObjectSet<Vendita> _Vendita;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Articoli EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToArticoli(Articoli articoli)
        {
            base.AddObject("Articoli", articoli);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Clienti EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClienti(Clienti clienti)
        {
            base.AddObject("Clienti", clienti);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Vendita EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVendita(Vendita vendita)
        {
            base.AddObject("Vendita", vendita);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="test3Model1", Name="Articoli")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Articoli : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Articoli object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static Articoli CreateArticoli(global::System.Guid id)
        {
            Articoli articoli = new Articoli();
            articoli.id = id;
            return articoli;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Guid _id;
        partial void OnidChanging(global::System.Guid value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descrizione
        {
            get
            {
                return _Descrizione;
            }
            set
            {
                OnDescrizioneChanging(value);
                ReportPropertyChanging("Descrizione");
                _Descrizione = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descrizione");
                OnDescrizioneChanged();
            }
        }
        private global::System.String _Descrizione;
        partial void OnDescrizioneChanging(global::System.String value);
        partial void OnDescrizioneChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="test3Model1", Name="Clienti")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Clienti : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Clienti object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static Clienti CreateClienti(global::System.Guid id)
        {
            Clienti clienti = new Clienti();
            clienti.id = id;
            return clienti;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Guid _id;
        partial void OnidChanging(global::System.Guid value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="test3Model1", Name="Vendita")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Vendita : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Vendita object.
        /// </summary>
        /// <param name="articolo">Initial value of the Articolo property.</param>
        /// <param name="cliente">Initial value of the Cliente property.</param>
        public static Vendita CreateVendita(global::System.Guid articolo, global::System.Guid cliente)
        {
            Vendita vendita = new Vendita();
            vendita.Articolo = articolo;
            vendita.Cliente = cliente;
            return vendita;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Articolo
        {
            get
            {
                return _Articolo;
            }
            set
            {
                if (_Articolo != value)
                {
                    OnArticoloChanging(value);
                    ReportPropertyChanging("Articolo");
                    _Articolo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Articolo");
                    OnArticoloChanged();
                }
            }
        }
        private global::System.Guid _Articolo;
        partial void OnArticoloChanging(global::System.Guid value);
        partial void OnArticoloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Cliente
        {
            get
            {
                return _Cliente;
            }
            set
            {
                if (_Cliente != value)
                {
                    OnClienteChanging(value);
                    ReportPropertyChanging("Cliente");
                    _Cliente = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Cliente");
                    OnClienteChanged();
                }
            }
        }
        private global::System.Guid _Cliente;
        partial void OnClienteChanging(global::System.Guid value);
        partial void OnClienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nota
        {
            get
            {
                return _Nota;
            }
            set
            {
                OnNotaChanging(value);
                ReportPropertyChanging("Nota");
                _Nota = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nota");
                OnNotaChanged();
            }
        }
        private global::System.String _Nota;
        partial void OnNotaChanging(global::System.String value);
        partial void OnNotaChanged();

        #endregion
    
    }

    #endregion
    
}
