//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace Digiphoto.Lumen.Model
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(RigaAlbum))]
    public partial class Album
    {
        public Album()
        {
            this.righeAlbum = new HashSet<RigaAlbum>();
        }
    
        [DataMember]
        public int id { get; set; }
        [DataMember]
        public string titolo { get; set; }
        [DataMember]
        public string note { get; set; }
        [DataMember]
        public System.DateTime timestamp { get; set; }
    
        [DataMember]
        public virtual ICollection<RigaAlbum> righeAlbum { get; set; }
    }
    
}
