//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Digiphoto.Lumen.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrello
    {
        public Carrello()
        {
            this.venduto = false;
            this.totMasterizzate = 0;
            this.righeCarrello = new HashSet<RigaCarrello>();
            this.incassiFotografi = new HashSet<IncassoFotografo>();
        }
    
        public System.Guid id { get; set; }
        public System.DateTime giornata { get; set; }
        public System.DateTime tempo { get; set; }
        public decimal totaleAPagare { get; set; }
        public string intestazione { get; set; }
        public bool venduto { get; set; }
        public string note { get; set; }
        public short totMasterizzate { get; set; }
        public Nullable<decimal> prezzoDischetto { get; set; }
    
        public virtual ICollection<RigaCarrello> righeCarrello { get; set; }
        public virtual ICollection<IncassoFotografo> incassiFotografi { get; set; }
    }
}
