//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Digiphoto.Lumen.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsumoCartaGiornaliero
    {
        public System.Guid id { get; set; }
        public System.DateTime giornata { get; set; }
        public short totFogli { get; set; }
        public short diCuiProvini { get; set; }
        public short diCuiFoto { get; set; }
    
        public virtual FormatoCarta formatoCarta { get; set; }
    }
}
