//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace Digiphoto.Lumen.Model
{
    [DataContract(IsReference = true)]
    public partial class FormatoCarta
    {
        public FormatoCarta()
        {
            this.attivo = true;
        }
    
        [DataMember]
        public System.Guid id { get; set; }
        [DataMember]
        public string descrizione { get; set; }
        [DataMember]
        public decimal prezzo { get; set; }
        [DataMember]
        public bool attivo { get; set; }
        [DataMember]
        public Nullable<short> ordinamento { get; set; }


		public override int GetHashCode() {
			return 17 + 31 * id.GetHashCode();
		}

		public override bool Equals( object obj ) {

			bool sonoUguali = false;

			if( obj is FormatoCarta ) {

				FormatoCarta altra = (FormatoCarta)obj;
				sonoUguali = this.id.Equals( altra.id );
			}

			return sonoUguali;
		}
    }
    
}
