//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace Digiphoto.Lumen.Model
{
    [DataContract(IsReference = true)]
    public partial class Fotografo
    {
        public Fotografo()
        {
            this.attivo = true;
            this.umano = true;
        }
    
        [DataMember]
        public string id { get; set; }
        [DataMember]
        public string cognomeNome { get; set; }
        [DataMember]
        public string iniziali { get; set; }
        [DataMember]
        public bool attivo { get; set; }
        [DataMember]
        public bool umano { get; set; }
        [DataMember]
        public string note { get; set; }
    }
    
}
