//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Digiphoto.Lumen.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Fotografo : INotifyPropertyChanged 
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fotografo()
        {
            this.attivo = true;
            this.umano = true;
        }
    
    	public string id { get; set; }
    	public string cognomeNome { get; set; }
    	public string iniziali { get; set; }
    	public bool attivo { get; set; }
    	public bool umano { get; set; }
    	public string note { get; set; }
    	public byte[] immagine { get; set; }

		#region INotifyPropertyChanged

		[field: NonSerialized]
		public event PropertyChangedEventHandler PropertyChanged;
    
    	protected void OnPropertyChanged(string propertyName)
    	{
    		OnPropertyChanged(new PropertyChangedEventArgs(propertyName));
    	}
    
    	protected virtual void OnPropertyChanged(PropertyChangedEventArgs e)
    	{
    		if (PropertyChanged != null)
    			PropertyChanged(this, e);
    	}
    	#endregion INotifyPropertyChanged	
    }
}
