//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace Digiphoto.Lumen.Model
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Fotografo))]
    [KnownType(typeof(Evento))]
    public partial class Fotografia
    {
        [DataMember]
        public System.Guid id { get; set; }
        [DataMember]
        public string nomeFile { get; set; }
        [DataMember]
        public Nullable<System.DateTime> dataOraScatto { get; set; }
        [DataMember]
        public string didascalia { get; set; }
        [DataMember]
        public System.DateTime dataOraAcquisizione { get; set; }
        [DataMember]
        public int numero { get; set; }
        [DataMember]
        public Nullable<short> faseDelGiorno { get; set; }
        [DataMember]
        public System.DateTime giornata { get; set; }
        [DataMember]
        public string correzioniXml { get; set; }
    
        [DataMember]
        public virtual Fotografo fotografo { get; set; }
        [DataMember]
        public virtual Evento evento { get; set; }
    }
    
}
