//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Digiphoto.Lumen.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncassoFotografo
    {
        public System.Guid Id { get; set; }
        public decimal incasso { get; set; }
        public decimal incassoStampe { get; set; }
        public decimal incassoMasterizzate { get; set; }
        public Nullable<short> contaStampe { get; set; }
        public short contaMasterizzate { get; set; }
        public Nullable<decimal> provvigioni { get; set; }
    
        public virtual Carrello carrello { get; set; }
        public virtual Fotografo fotografo { get; set; }
    }
}
