//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Digiphoto.Lumen.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class InfoFissa : INotifyPropertyChanged 
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InfoFissa()
        {
            this.id = "K";
            this.versioneDbCompatibile = "1.1";
            this.modoNumerazFoto = "X";
        }
    
    	public string id { get; set; }
    	public int ultimoNumFotogramma { get; set; }
    	public Nullable<System.DateTime> dataUltimoScarico { get; set; }
    	public string versioneDbCompatibile { get; set; }
    	public string modoNumerazFoto { get; set; }
    	public short pixelProvino { get; set; }
    	public string idPuntoVendita { get; set; }
    	public string descrizPuntoVendita { get; set; }
    	public short numGiorniEliminaFoto { get; set; }
    	public string varie { get; set; }
    
    	#region INotifyPropertyChanged
    	public event PropertyChangedEventHandler PropertyChanged;
    
    	protected void OnPropertyChanged(string propertyName)
    	{
    		OnPropertyChanged(new PropertyChangedEventArgs(propertyName));
    	}
    
    	protected virtual void OnPropertyChanged(PropertyChangedEventArgs e)
    	{
    		if (PropertyChanged != null)
    			PropertyChanged(this, e);
    	}
    	#endregion INotifyPropertyChanged	
    }
}
