//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Digiphoto.Lumen.Model", "FotografoFotografia", "Fotografo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Digiphoto.Lumen.Model.Fotografo), "Fotografia", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Digiphoto.Lumen.Model.Fotografia))]
[assembly: EdmRelationshipAttribute("Digiphoto.Lumen.Model", "EventoFotografia", "Evento", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Digiphoto.Lumen.Model.Evento), "Fotografia", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Digiphoto.Lumen.Model.Fotografia))]
[assembly: EdmRelationshipAttribute("Digiphoto.Lumen.Model", "AlbumRigaAlbum", "Album", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Digiphoto.Lumen.Model.Album), "RigaAlbum", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Digiphoto.Lumen.Model.RigaAlbum))]
[assembly: EdmRelationshipAttribute("Digiphoto.Lumen.Model", "FotografoScaricoCard", "Fotografo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Digiphoto.Lumen.Model.Fotografo), "ScaricoCard", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Digiphoto.Lumen.Model.ScaricoCard))]
[assembly: EdmRelationshipAttribute("Digiphoto.Lumen.Model", "CarrelloRigaCarrello", "Carrello", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Digiphoto.Lumen.Model.Carrello), "RigaCarrello", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Digiphoto.Lumen.Model.RigaCarrello))]
[assembly: EdmRelationshipAttribute("Digiphoto.Lumen.Model", "FormatoCartaRiCaFotoStampata", "FormatoCarta", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Digiphoto.Lumen.Model.FormatoCarta), "RiCaFotoStampata", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Digiphoto.Lumen.Model.RiCaFotoStampata))]
[assembly: EdmRelationshipAttribute("Digiphoto.Lumen.Model", "FotografoRiCaFotoStampata", "Fotografo", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Digiphoto.Lumen.Model.Fotografo), "RiCaFotoStampata", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Digiphoto.Lumen.Model.RiCaFotoStampata))]
[assembly: EdmRelationshipAttribute("Digiphoto.Lumen.Model", "FotografiaRigaAlbum", "Fotografia", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Digiphoto.Lumen.Model.Fotografia), "RigaAlbum", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Digiphoto.Lumen.Model.RigaAlbum))]

#endregion

namespace Digiphoto.Lumen.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class LumenEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new LumenEntities object using the connection string found in the 'LumenEntities' section of the application configuration file.
        /// </summary>
        public LumenEntities() : base("name=LumenEntities", "LumenEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LumenEntities object.
        /// </summary>
        public LumenEntities(string connectionString) : base(connectionString, "LumenEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LumenEntities object.
        /// </summary>
        public LumenEntities(EntityConnection connection) : base(connection, "LumenEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Fotografo> Fotografi
        {
            get
            {
                if ((_Fotografi == null))
                {
                    _Fotografi = base.CreateObjectSet<Fotografo>("Fotografi");
                }
                return _Fotografi;
            }
        }
        private ObjectSet<Fotografo> _Fotografi;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Fotografia> Fotografie
        {
            get
            {
                if ((_Fotografie == null))
                {
                    _Fotografie = base.CreateObjectSet<Fotografia>("Fotografie");
                }
                return _Fotografie;
            }
        }
        private ObjectSet<Fotografia> _Fotografie;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Evento> Eventi
        {
            get
            {
                if ((_Eventi == null))
                {
                    _Eventi = base.CreateObjectSet<Evento>("Eventi");
                }
                return _Eventi;
            }
        }
        private ObjectSet<Evento> _Eventi;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Album> Albums
        {
            get
            {
                if ((_Albums == null))
                {
                    _Albums = base.CreateObjectSet<Album>("Albums");
                }
                return _Albums;
            }
        }
        private ObjectSet<Album> _Albums;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RigaAlbum> RigheAlbum
        {
            get
            {
                if ((_RigheAlbum == null))
                {
                    _RigheAlbum = base.CreateObjectSet<RigaAlbum>("RigheAlbum");
                }
                return _RigheAlbum;
            }
        }
        private ObjectSet<RigaAlbum> _RigheAlbum;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ScaricoCard> ScarichiCards
        {
            get
            {
                if ((_ScarichiCards == null))
                {
                    _ScarichiCards = base.CreateObjectSet<ScaricoCard>("ScarichiCards");
                }
                return _ScarichiCards;
            }
        }
        private ObjectSet<ScaricoCard> _ScarichiCards;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FormatoCarta> FormatiCarta
        {
            get
            {
                if ((_FormatiCarta == null))
                {
                    _FormatiCarta = base.CreateObjectSet<FormatoCarta>("FormatiCarta");
                }
                return _FormatiCarta;
            }
        }
        private ObjectSet<FormatoCarta> _FormatiCarta;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<InfoFissa> InfosFisse
        {
            get
            {
                if ((_InfosFisse == null))
                {
                    _InfosFisse = base.CreateObjectSet<InfoFissa>("InfosFisse");
                }
                return _InfosFisse;
            }
        }
        private ObjectSet<InfoFissa> _InfosFisse;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Carrello> Carrelli
        {
            get
            {
                if ((_Carrelli == null))
                {
                    _Carrelli = base.CreateObjectSet<Carrello>("Carrelli");
                }
                return _Carrelli;
            }
        }
        private ObjectSet<Carrello> _Carrelli;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RigaCarrello> RigheCarrelli
        {
            get
            {
                if ((_RigheCarrelli == null))
                {
                    _RigheCarrelli = base.CreateObjectSet<RigaCarrello>("RigheCarrelli");
                }
                return _RigheCarrelli;
            }
        }
        private ObjectSet<RigaCarrello> _RigheCarrelli;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Fotografi EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFotografi(Fotografo fotografo)
        {
            base.AddObject("Fotografi", fotografo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Fotografie EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFotografie(Fotografia fotografia)
        {
            base.AddObject("Fotografie", fotografia);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Eventi EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEventi(Evento evento)
        {
            base.AddObject("Eventi", evento);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Albums EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAlbums(Album album)
        {
            base.AddObject("Albums", album);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RigheAlbum EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRigheAlbum(RigaAlbum rigaAlbum)
        {
            base.AddObject("RigheAlbum", rigaAlbum);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ScarichiCards EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToScarichiCards(ScaricoCard scaricoCard)
        {
            base.AddObject("ScarichiCards", scaricoCard);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FormatiCarta EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFormatiCarta(FormatoCarta formatoCarta)
        {
            base.AddObject("FormatiCarta", formatoCarta);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the InfosFisse EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToInfosFisse(InfoFissa infoFissa)
        {
            base.AddObject("InfosFisse", infoFissa);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Carrelli EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCarrelli(Carrello carrello)
        {
            base.AddObject("Carrelli", carrello);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RigheCarrelli EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRigheCarrelli(RigaCarrello rigaCarrello)
        {
            base.AddObject("RigheCarrelli", rigaCarrello);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Digiphoto.Lumen.Model", Name="Album")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Album : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Album object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="titolo">Initial value of the titolo property.</param>
        /// <param name="note">Initial value of the note property.</param>
        /// <param name="timestamp">Initial value of the timestamp property.</param>
        public static Album CreateAlbum(global::System.Int32 id, global::System.String titolo, global::System.String note, global::System.DateTime timestamp)
        {
            Album album = new Album();
            album.id = id;
            album.titolo = titolo;
            album.note = note;
            album.timestamp = timestamp;
            return album;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String titolo
        {
            get
            {
                return _titolo;
            }
            set
            {
                OntitoloChanging(value);
                ReportPropertyChanging("titolo");
                _titolo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("titolo");
                OntitoloChanged();
            }
        }
        private global::System.String _titolo;
        partial void OntitoloChanging(global::System.String value);
        partial void OntitoloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String note
        {
            get
            {
                return _note;
            }
            set
            {
                OnnoteChanging(value);
                ReportPropertyChanging("note");
                _note = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("note");
                OnnoteChanged();
            }
        }
        private global::System.String _note;
        partial void OnnoteChanging(global::System.String value);
        partial void OnnoteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime timestamp
        {
            get
            {
                return _timestamp;
            }
            set
            {
                OntimestampChanging(value);
                ReportPropertyChanging("timestamp");
                _timestamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("timestamp");
                OntimestampChanged();
            }
        }
        private global::System.DateTime _timestamp;
        partial void OntimestampChanging(global::System.DateTime value);
        partial void OntimestampChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Digiphoto.Lumen.Model", "AlbumRigaAlbum", "RigaAlbum")]
        public EntityCollection<RigaAlbum> righeAlbum
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RigaAlbum>("Digiphoto.Lumen.Model.AlbumRigaAlbum", "RigaAlbum");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RigaAlbum>("Digiphoto.Lumen.Model.AlbumRigaAlbum", "RigaAlbum", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Digiphoto.Lumen.Model", Name="Carrello")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Carrello : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Carrello object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="giornata">Initial value of the giornata property.</param>
        /// <param name="tempo">Initial value of the tempo property.</param>
        /// <param name="totaleAPagare">Initial value of the totaleAPagare property.</param>
        public static Carrello CreateCarrello(global::System.Guid id, global::System.DateTime giornata, global::System.DateTime tempo, global::System.Decimal totaleAPagare)
        {
            Carrello carrello = new Carrello();
            carrello.id = id;
            carrello.giornata = giornata;
            carrello.tempo = tempo;
            carrello.totaleAPagare = totaleAPagare;
            return carrello;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Guid _id;
        partial void OnidChanging(global::System.Guid value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime giornata
        {
            get
            {
                return _giornata;
            }
            set
            {
                OngiornataChanging(value);
                ReportPropertyChanging("giornata");
                _giornata = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("giornata");
                OngiornataChanged();
            }
        }
        private global::System.DateTime _giornata;
        partial void OngiornataChanging(global::System.DateTime value);
        partial void OngiornataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime tempo
        {
            get
            {
                return _tempo;
            }
            set
            {
                OntempoChanging(value);
                ReportPropertyChanging("tempo");
                _tempo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tempo");
                OntempoChanged();
            }
        }
        private global::System.DateTime _tempo;
        partial void OntempoChanging(global::System.DateTime value);
        partial void OntempoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal totaleAPagare
        {
            get
            {
                return _totaleAPagare;
            }
            set
            {
                OntotaleAPagareChanging(value);
                ReportPropertyChanging("totaleAPagare");
                _totaleAPagare = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("totaleAPagare");
                OntotaleAPagareChanged();
            }
        }
        private global::System.Decimal _totaleAPagare;
        partial void OntotaleAPagareChanging(global::System.Decimal value);
        partial void OntotaleAPagareChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Digiphoto.Lumen.Model", "CarrelloRigaCarrello", "RigaCarrello")]
        public EntityCollection<RigaCarrello> righeCarrello
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RigaCarrello>("Digiphoto.Lumen.Model.CarrelloRigaCarrello", "RigaCarrello");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RigaCarrello>("Digiphoto.Lumen.Model.CarrelloRigaCarrello", "RigaCarrello", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Digiphoto.Lumen.Model", Name="Evento")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Evento : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Evento object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="descrizione">Initial value of the descrizione property.</param>
        public static Evento CreateEvento(global::System.Guid id, global::System.String descrizione)
        {
            Evento evento = new Evento();
            evento.id = id;
            evento.descrizione = descrizione;
            return evento;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Guid _id;
        partial void OnidChanging(global::System.Guid value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descrizione
        {
            get
            {
                return _descrizione;
            }
            set
            {
                OndescrizioneChanging(value);
                ReportPropertyChanging("descrizione");
                _descrizione = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descrizione");
                OndescrizioneChanged();
            }
        }
        private global::System.String _descrizione;
        partial void OndescrizioneChanging(global::System.String value);
        partial void OndescrizioneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean attivo
        {
            get
            {
                return _attivo;
            }
            set
            {
                OnattivoChanging(value);
                ReportPropertyChanging("attivo");
                _attivo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("attivo");
                OnattivoChanged();
            }
        }
        private global::System.Boolean _attivo = true;
        partial void OnattivoChanging(global::System.Boolean value);
        partial void OnattivoChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Digiphoto.Lumen.Model", Name="FormatoCarta")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FormatoCarta : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FormatoCarta object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="descrizione">Initial value of the descrizione property.</param>
        /// <param name="prezzo">Initial value of the prezzo property.</param>
        public static FormatoCarta CreateFormatoCarta(global::System.Guid id, global::System.String descrizione, global::System.Decimal prezzo)
        {
            FormatoCarta formatoCarta = new FormatoCarta();
            formatoCarta.id = id;
            formatoCarta.descrizione = descrizione;
            formatoCarta.prezzo = prezzo;
            return formatoCarta;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Guid _id;
        partial void OnidChanging(global::System.Guid value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descrizione
        {
            get
            {
                return _descrizione;
            }
            set
            {
                OndescrizioneChanging(value);
                ReportPropertyChanging("descrizione");
                _descrizione = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descrizione");
                OndescrizioneChanged();
            }
        }
        private global::System.String _descrizione;
        partial void OndescrizioneChanging(global::System.String value);
        partial void OndescrizioneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal prezzo
        {
            get
            {
                return _prezzo;
            }
            set
            {
                OnprezzoChanging(value);
                ReportPropertyChanging("prezzo");
                _prezzo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("prezzo");
                OnprezzoChanged();
            }
        }
        private global::System.Decimal _prezzo;
        partial void OnprezzoChanging(global::System.Decimal value);
        partial void OnprezzoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Digiphoto.Lumen.Model", "FormatoCartaRiCaFotoStampata", "RiCaFotoStampata")]
        public EntityCollection<RiCaFotoStampata> RiCaFotoStampata
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RiCaFotoStampata>("Digiphoto.Lumen.Model.FormatoCartaRiCaFotoStampata", "RiCaFotoStampata");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RiCaFotoStampata>("Digiphoto.Lumen.Model.FormatoCartaRiCaFotoStampata", "RiCaFotoStampata", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Digiphoto.Lumen.Model", Name="Fotografia")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Fotografia : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Fotografia object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="nomeFile">Initial value of the nomeFile property.</param>
        /// <param name="dataOraAcquisizione">Initial value of the dataOraAcquisizione property.</param>
        /// <param name="numero">Initial value of the numero property.</param>
        public static Fotografia CreateFotografia(global::System.Guid id, global::System.String nomeFile, global::System.DateTime dataOraAcquisizione, global::System.Int32 numero)
        {
            Fotografia fotografia = new Fotografia();
            fotografia.id = id;
            fotografia.nomeFile = nomeFile;
            fotografia.dataOraAcquisizione = dataOraAcquisizione;
            fotografia.numero = numero;
            return fotografia;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Guid _id;
        partial void OnidChanging(global::System.Guid value);
        partial void OnidChanged();
    
        /// <summary>
        /// nome del file senza il percorso
        /// </summary>
        /// <LongDescription>
        /// E&apos; il nome originale del file cosi come generato dalla fotocamera
        /// </LongDescription>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nomeFile
        {
            get
            {
                return _nomeFile;
            }
            set
            {
                OnnomeFileChanging(value);
                ReportPropertyChanging("nomeFile");
                _nomeFile = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nomeFile");
                OnnomeFileChanged();
            }
        }
        private global::System.String _nomeFile;
        partial void OnnomeFileChanging(global::System.String value);
        partial void OnnomeFileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dataOraScatto
        {
            get
            {
                return _dataOraScatto;
            }
            set
            {
                OndataOraScattoChanging(value);
                ReportPropertyChanging("dataOraScatto");
                _dataOraScatto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dataOraScatto");
                OndataOraScattoChanged();
            }
        }
        private Nullable<global::System.DateTime> _dataOraScatto;
        partial void OndataOraScattoChanging(Nullable<global::System.DateTime> value);
        partial void OndataOraScattoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String didascalia
        {
            get
            {
                return _didascalia;
            }
            set
            {
                OndidascaliaChanging(value);
                ReportPropertyChanging("didascalia");
                _didascalia = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("didascalia");
                OndidascaliaChanged();
            }
        }
        private global::System.String _didascalia;
        partial void OndidascaliaChanging(global::System.String value);
        partial void OndidascaliaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime dataOraAcquisizione
        {
            get
            {
                return _dataOraAcquisizione;
            }
            set
            {
                OndataOraAcquisizioneChanging(value);
                ReportPropertyChanging("dataOraAcquisizione");
                _dataOraAcquisizione = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dataOraAcquisizione");
                OndataOraAcquisizioneChanged();
            }
        }
        private global::System.DateTime _dataOraAcquisizione;
        partial void OndataOraAcquisizioneChanging(global::System.DateTime value);
        partial void OndataOraAcquisizioneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String correzioni
        {
            get
            {
                return _correzioni;
            }
            set
            {
                OncorrezioniChanging(value);
                ReportPropertyChanging("correzioni");
                _correzioni = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("correzioni");
                OncorrezioniChanged();
            }
        }
        private global::System.String _correzioni;
        partial void OncorrezioniChanging(global::System.String value);
        partial void OncorrezioniChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 numero
        {
            get
            {
                return _numero;
            }
            set
            {
                OnnumeroChanging(value);
                ReportPropertyChanging("numero");
                _numero = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("numero");
                OnnumeroChanged();
            }
        }
        private global::System.Int32 _numero;
        partial void OnnumeroChanging(global::System.Int32 value);
        partial void OnnumeroChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Digiphoto.Lumen.Model", "FotografoFotografia", "Fotografo")]
        public Fotografo fotografo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Fotografo>("Digiphoto.Lumen.Model.FotografoFotografia", "Fotografo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Fotografo>("Digiphoto.Lumen.Model.FotografoFotografia", "Fotografo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Fotografo> fotografoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Fotografo>("Digiphoto.Lumen.Model.FotografoFotografia", "Fotografo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Fotografo>("Digiphoto.Lumen.Model.FotografoFotografia", "Fotografo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Digiphoto.Lumen.Model", "EventoFotografia", "Evento")]
        public Evento evento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Evento>("Digiphoto.Lumen.Model.EventoFotografia", "Evento").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Evento>("Digiphoto.Lumen.Model.EventoFotografia", "Evento").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Evento> eventoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Evento>("Digiphoto.Lumen.Model.EventoFotografia", "Evento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Evento>("Digiphoto.Lumen.Model.EventoFotografia", "Evento", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Operatori scattini e fotografi
    /// </summary>
    /// <LongDescription>
    /// Anagrafica dei fotografi che producono foto
    /// </LongDescription>
    [EdmEntityTypeAttribute(NamespaceName="Digiphoto.Lumen.Model", Name="Fotografo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Fotografo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Fotografo object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="cognomeNome">Initial value of the cognomeNome property.</param>
        /// <param name="iniziali">Initial value of the iniziali property.</param>
        public static Fotografo CreateFotografo(global::System.String id, global::System.String cognomeNome, global::System.String iniziali)
        {
            Fotografo fotografo = new Fotografo();
            fotografo.id = id;
            fotografo.cognomeNome = cognomeNome;
            fotografo.iniziali = iniziali;
            return fotografo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// Identificatico univoco del fotografo in tutte le installazioni
        /// </summary>
        /// <LongDescription>
        /// Utilizzare per esempio il codice fiscale
        /// </LongDescription>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.String _id;
        partial void OnidChanging(global::System.String value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cognomeNome
        {
            get
            {
                return _cognomeNome;
            }
            set
            {
                OncognomeNomeChanging(value);
                ReportPropertyChanging("cognomeNome");
                _cognomeNome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("cognomeNome");
                OncognomeNomeChanged();
            }
        }
        private global::System.String _cognomeNome;
        partial void OncognomeNomeChanging(global::System.String value);
        partial void OncognomeNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String iniziali
        {
            get
            {
                return _iniziali;
            }
            set
            {
                OninizialiChanging(value);
                ReportPropertyChanging("iniziali");
                _iniziali = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("iniziali");
                OninizialiChanged();
            }
        }
        private global::System.String _iniziali;
        partial void OninizialiChanging(global::System.String value);
        partial void OninizialiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean attivo
        {
            get
            {
                return _attivo;
            }
            set
            {
                OnattivoChanging(value);
                ReportPropertyChanging("attivo");
                _attivo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("attivo");
                OnattivoChanged();
            }
        }
        private global::System.Boolean _attivo = true;
        partial void OnattivoChanging(global::System.Boolean value);
        partial void OnattivoChanged();
    
        /// <summary>
        /// Umano oppure Automatico (OnRide)
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean umano
        {
            get
            {
                return _umano;
            }
            set
            {
                OnumanoChanging(value);
                ReportPropertyChanging("umano");
                _umano = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("umano");
                OnumanoChanged();
            }
        }
        private global::System.Boolean _umano = true;
        partial void OnumanoChanging(global::System.Boolean value);
        partial void OnumanoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String note
        {
            get
            {
                return _note;
            }
            set
            {
                OnnoteChanging(value);
                ReportPropertyChanging("note");
                _note = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("note");
                OnnoteChanged();
            }
        }
        private global::System.String _note;
        partial void OnnoteChanging(global::System.String value);
        partial void OnnoteChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Digiphoto.Lumen.Model", Name="InfoFissa")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class InfoFissa : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new InfoFissa object.
        /// </summary>
        /// <param name="ultimoNumFotogramma">Initial value of the ultimoNumFotogramma property.</param>
        public static InfoFissa CreateInfoFissa(global::System.Int32 ultimoNumFotogramma)
        {
            InfoFissa infoFissa = new InfoFissa();
            infoFissa.ultimoNumFotogramma = ultimoNumFotogramma;
            return infoFissa;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// Informazioni fisse per tutti gli utenti
        /// </summary>
        /// <LongDescription>
        /// Tabella a record unico. Tutti gli utenti vedono lo stessa unica riga
        /// </LongDescription>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.String _id = "K";
        partial void OnidChanging(global::System.String value);
        partial void OnidChanged();
    
        /// <summary>
        /// 
        /// </summary>
        /// <LongDescription>
        /// A tutti gli effetti la usiamo come una sequence
        /// </LongDescription>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ultimoNumFotogramma
        {
            get
            {
                return _ultimoNumFotogramma;
            }
            set
            {
                OnultimoNumFotogrammaChanging(value);
                ReportPropertyChanging("ultimoNumFotogramma");
                _ultimoNumFotogramma = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ultimoNumFotogramma");
                OnultimoNumFotogrammaChanged();
            }
        }
        private global::System.Int32 _ultimoNumFotogramma;
        partial void OnultimoNumFotogrammaChanging(global::System.Int32 value);
        partial void OnultimoNumFotogrammaChanged();
    
        /// <summary>
        /// 
        /// </summary>
        /// <LongDescription>
        /// Data senza ora dell&apos;ultima volta in cui ho incrementato il numeratore delle foto (sequenza)
        /// </LongDescription>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dataUltimoScarico
        {
            get
            {
                return _dataUltimoScarico;
            }
            set
            {
                OndataUltimoScaricoChanging(value);
                ReportPropertyChanging("dataUltimoScarico");
                _dataUltimoScarico = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dataUltimoScarico");
                OndataUltimoScaricoChanged();
            }
        }
        private Nullable<global::System.DateTime> _dataUltimoScarico;
        partial void OndataUltimoScaricoChanging(Nullable<global::System.DateTime> value);
        partial void OndataUltimoScaricoChanged();
    
        /// <summary>
        /// 
        /// </summary>
        /// <LongDescription>
        /// Indica il numero di revisione della struttura del database. Il programma qando parte deve controllare di essere compatibile
        /// </LongDescription>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String versioneDbCompatibile
        {
            get
            {
                return _versioneDbCompatibile;
            }
            set
            {
                OnversioneDbCompatibileChanging(value);
                ReportPropertyChanging("versioneDbCompatibile");
                _versioneDbCompatibile = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("versioneDbCompatibile");
                OnversioneDbCompatibileChanged();
            }
        }
        private global::System.String _versioneDbCompatibile = "1.0";
        partial void OnversioneDbCompatibileChanging(global::System.String value);
        partial void OnversioneDbCompatibileChanged();
    
        /// <summary>
        /// Modo azzeramento sequenza fotogrammi
        /// </summary>
        /// <LongDescription>
        /// Ogni foto che entra, viene numerata. Questo numeratore può essere azzerato in vari modi:&#xA; G = ogni giorno&#xA; S = ogni settimana&#xA; M = mai
        /// </LongDescription>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String modoNumerazione
        {
            get
            {
                return _modoNumerazione;
            }
            set
            {
                OnmodoNumerazioneChanging(value);
                ReportPropertyChanging("modoNumerazione");
                _modoNumerazione = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("modoNumerazione");
                OnmodoNumerazioneChanged();
            }
        }
        private global::System.String _modoNumerazione = "M";
        partial void OnmodoNumerazioneChanging(global::System.String value);
        partial void OnmodoNumerazioneChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Digiphoto.Lumen.Model", Name="RiCaDiscoMasterizzato")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RiCaDiscoMasterizzato : RigaCarrello
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RiCaDiscoMasterizzato object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="prezzoLordoUnitario">Initial value of the prezzoLordoUnitario property.</param>
        /// <param name="quantita">Initial value of the quantita property.</param>
        /// <param name="prezzoNettoTotale">Initial value of the prezzoNettoTotale property.</param>
        /// <param name="descrizione">Initial value of the descrizione property.</param>
        public static RiCaDiscoMasterizzato CreateRiCaDiscoMasterizzato(global::System.Guid id, global::System.Decimal prezzoLordoUnitario, global::System.Int16 quantita, global::System.Decimal prezzoNettoTotale, global::System.String descrizione)
        {
            RiCaDiscoMasterizzato riCaDiscoMasterizzato = new RiCaDiscoMasterizzato();
            riCaDiscoMasterizzato.id = id;
            riCaDiscoMasterizzato.prezzoLordoUnitario = prezzoLordoUnitario;
            riCaDiscoMasterizzato.quantita = quantita;
            riCaDiscoMasterizzato.prezzoNettoTotale = prezzoNettoTotale;
            riCaDiscoMasterizzato.descrizione = descrizione;
            return riCaDiscoMasterizzato;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> totFotoMasterizzate
        {
            get
            {
                return _totFotoMasterizzate;
            }
            set
            {
                OntotFotoMasterizzateChanging(value);
                ReportPropertyChanging("totFotoMasterizzate");
                _totFotoMasterizzate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("totFotoMasterizzate");
                OntotFotoMasterizzateChanged();
            }
        }
        private Nullable<global::System.Int16> _totFotoMasterizzate;
        partial void OntotFotoMasterizzateChanging(Nullable<global::System.Int16> value);
        partial void OntotFotoMasterizzateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Digiphoto.Lumen.Model", Name="RiCaFotoStampata")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RiCaFotoStampata : RigaCarrello
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RiCaFotoStampata object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="prezzoLordoUnitario">Initial value of the prezzoLordoUnitario property.</param>
        /// <param name="quantita">Initial value of the quantita property.</param>
        /// <param name="prezzoNettoTotale">Initial value of the prezzoNettoTotale property.</param>
        /// <param name="descrizione">Initial value of the descrizione property.</param>
        public static RiCaFotoStampata CreateRiCaFotoStampata(global::System.Guid id, global::System.Decimal prezzoLordoUnitario, global::System.Int16 quantita, global::System.Decimal prezzoNettoTotale, global::System.String descrizione)
        {
            RiCaFotoStampata riCaFotoStampata = new RiCaFotoStampata();
            riCaFotoStampata.id = id;
            riCaFotoStampata.prezzoLordoUnitario = prezzoLordoUnitario;
            riCaFotoStampata.quantita = quantita;
            riCaFotoStampata.prezzoNettoTotale = prezzoNettoTotale;
            riCaFotoStampata.descrizione = descrizione;
            return riCaFotoStampata;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> totFogliStampati
        {
            get
            {
                return _totFogliStampati;
            }
            set
            {
                OntotFogliStampatiChanging(value);
                ReportPropertyChanging("totFogliStampati");
                _totFogliStampati = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("totFogliStampati");
                OntotFogliStampatiChanged();
            }
        }
        private Nullable<global::System.Int16> _totFogliStampati;
        partial void OntotFogliStampatiChanging(Nullable<global::System.Int16> value);
        partial void OntotFogliStampatiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> idFotografia
        {
            get
            {
                return _idFotografia;
            }
            set
            {
                OnidFotografiaChanging(value);
                ReportPropertyChanging("idFotografia");
                _idFotografia = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idFotografia");
                OnidFotografiaChanged();
            }
        }
        private Nullable<global::System.Guid> _idFotografia;
        partial void OnidFotografiaChanging(Nullable<global::System.Guid> value);
        partial void OnidFotografiaChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Digiphoto.Lumen.Model", "FormatoCartaRiCaFotoStampata", "FormatoCarta")]
        public FormatoCarta formatoCarta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FormatoCarta>("Digiphoto.Lumen.Model.FormatoCartaRiCaFotoStampata", "FormatoCarta").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FormatoCarta>("Digiphoto.Lumen.Model.FormatoCartaRiCaFotoStampata", "FormatoCarta").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<FormatoCarta> formatoCartaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FormatoCarta>("Digiphoto.Lumen.Model.FormatoCartaRiCaFotoStampata", "FormatoCarta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<FormatoCarta>("Digiphoto.Lumen.Model.FormatoCartaRiCaFotoStampata", "FormatoCarta", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Digiphoto.Lumen.Model", "FotografoRiCaFotoStampata", "Fotografo")]
        public Fotografo fotografo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Fotografo>("Digiphoto.Lumen.Model.FotografoRiCaFotoStampata", "Fotografo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Fotografo>("Digiphoto.Lumen.Model.FotografoRiCaFotoStampata", "Fotografo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Fotografo> fotografoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Fotografo>("Digiphoto.Lumen.Model.FotografoRiCaFotoStampata", "Fotografo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Fotografo>("Digiphoto.Lumen.Model.FotografoRiCaFotoStampata", "Fotografo", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Digiphoto.Lumen.Model", Name="RigaAlbum")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RigaAlbum : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RigaAlbum object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static RigaAlbum CreateRigaAlbum(global::System.Int32 id)
        {
            RigaAlbum rigaAlbum = new RigaAlbum();
            rigaAlbum.id = id;
            return rigaAlbum;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Digiphoto.Lumen.Model", "FotografiaRigaAlbum", "Fotografia")]
        public Fotografia fotografia
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Fotografia>("Digiphoto.Lumen.Model.FotografiaRigaAlbum", "Fotografia").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Fotografia>("Digiphoto.Lumen.Model.FotografiaRigaAlbum", "Fotografia").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Fotografia> fotografiaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Fotografia>("Digiphoto.Lumen.Model.FotografiaRigaAlbum", "Fotografia");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Fotografia>("Digiphoto.Lumen.Model.FotografiaRigaAlbum", "Fotografia", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Digiphoto.Lumen.Model", Name="RigaCarrello")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(RiCaFotoStampata))]
    [KnownTypeAttribute(typeof(RiCaDiscoMasterizzato))]
    public partial class RigaCarrello : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RigaCarrello object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="prezzoLordoUnitario">Initial value of the prezzoLordoUnitario property.</param>
        /// <param name="quantita">Initial value of the quantita property.</param>
        /// <param name="prezzoNettoTotale">Initial value of the prezzoNettoTotale property.</param>
        /// <param name="descrizione">Initial value of the descrizione property.</param>
        public static RigaCarrello CreateRigaCarrello(global::System.Guid id, global::System.Decimal prezzoLordoUnitario, global::System.Int16 quantita, global::System.Decimal prezzoNettoTotale, global::System.String descrizione)
        {
            RigaCarrello rigaCarrello = new RigaCarrello();
            rigaCarrello.id = id;
            rigaCarrello.prezzoLordoUnitario = prezzoLordoUnitario;
            rigaCarrello.quantita = quantita;
            rigaCarrello.prezzoNettoTotale = prezzoNettoTotale;
            rigaCarrello.descrizione = descrizione;
            return rigaCarrello;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Guid _id;
        partial void OnidChanging(global::System.Guid value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal prezzoLordoUnitario
        {
            get
            {
                return _prezzoLordoUnitario;
            }
            set
            {
                OnprezzoLordoUnitarioChanging(value);
                ReportPropertyChanging("prezzoLordoUnitario");
                _prezzoLordoUnitario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("prezzoLordoUnitario");
                OnprezzoLordoUnitarioChanged();
            }
        }
        private global::System.Decimal _prezzoLordoUnitario;
        partial void OnprezzoLordoUnitarioChanging(global::System.Decimal value);
        partial void OnprezzoLordoUnitarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 quantita
        {
            get
            {
                return _quantita;
            }
            set
            {
                OnquantitaChanging(value);
                ReportPropertyChanging("quantita");
                _quantita = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("quantita");
                OnquantitaChanged();
            }
        }
        private global::System.Int16 _quantita;
        partial void OnquantitaChanging(global::System.Int16 value);
        partial void OnquantitaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal prezzoNettoTotale
        {
            get
            {
                return _prezzoNettoTotale;
            }
            set
            {
                OnprezzoNettoTotaleChanging(value);
                ReportPropertyChanging("prezzoNettoTotale");
                _prezzoNettoTotale = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("prezzoNettoTotale");
                OnprezzoNettoTotaleChanged();
            }
        }
        private global::System.Decimal _prezzoNettoTotale;
        partial void OnprezzoNettoTotaleChanging(global::System.Decimal value);
        partial void OnprezzoNettoTotaleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> sconto
        {
            get
            {
                return _sconto;
            }
            set
            {
                OnscontoChanging(value);
                ReportPropertyChanging("sconto");
                _sconto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sconto");
                OnscontoChanged();
            }
        }
        private Nullable<global::System.Decimal> _sconto;
        partial void OnscontoChanging(Nullable<global::System.Decimal> value);
        partial void OnscontoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descrizione
        {
            get
            {
                return _descrizione;
            }
            set
            {
                OndescrizioneChanging(value);
                ReportPropertyChanging("descrizione");
                _descrizione = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descrizione");
                OndescrizioneChanged();
            }
        }
        private global::System.String _descrizione;
        partial void OndescrizioneChanging(global::System.String value);
        partial void OndescrizioneChanged();

        #endregion
    
    }
    
    /// <summary>
    /// Foto Scattate
    /// </summary>
    /// <LongDescription>
    /// Questa entità rappresenta l&apos;azione di scaricare una memory card nel computer. In pratica sono le foto che un fotografo ha scattato in un periodo
    /// </LongDescription>
    [EdmEntityTypeAttribute(NamespaceName="Digiphoto.Lumen.Model", Name="ScaricoCard")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ScaricoCard : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ScaricoCard object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="tempo">Initial value of the tempo property.</param>
        /// <param name="totFoto">Initial value of the totFoto property.</param>
        public static ScaricoCard CreateScaricoCard(global::System.Guid id, global::System.DateTime tempo, global::System.Int16 totFoto)
        {
            ScaricoCard scaricoCard = new ScaricoCard();
            scaricoCard.id = id;
            scaricoCard.tempo = tempo;
            scaricoCard.totFoto = totFoto;
            return scaricoCard;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Guid _id;
        partial void OnidChanging(global::System.Guid value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime tempo
        {
            get
            {
                return _tempo;
            }
            set
            {
                OntempoChanging(value);
                ReportPropertyChanging("tempo");
                _tempo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tempo");
                OntempoChanged();
            }
        }
        private global::System.DateTime _tempo;
        partial void OntempoChanging(global::System.DateTime value);
        partial void OntempoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 totFoto
        {
            get
            {
                return _totFoto;
            }
            set
            {
                OntotFotoChanging(value);
                ReportPropertyChanging("totFoto");
                _totFoto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("totFoto");
                OntotFotoChanged();
            }
        }
        private global::System.Int16 _totFoto;
        partial void OntotFotoChanging(global::System.Int16 value);
        partial void OntotFotoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Digiphoto.Lumen.Model", "FotografoScaricoCard", "Fotografo")]
        public Fotografo fotografo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Fotografo>("Digiphoto.Lumen.Model.FotografoScaricoCard", "Fotografo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Fotografo>("Digiphoto.Lumen.Model.FotografoScaricoCard", "Fotografo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Fotografo> fotografoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Fotografo>("Digiphoto.Lumen.Model.FotografoScaricoCard", "Fotografo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Fotografo>("Digiphoto.Lumen.Model.FotografoScaricoCard", "Fotografo", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
