//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Digiphoto.Lumen.Model", "FotografoFotografia", "Fotografo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Digiphoto.Lumen.Model.Fotografo), "Fotografia", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Digiphoto.Lumen.Model.Fotografia))]
[assembly: EdmRelationshipAttribute("Digiphoto.Lumen.Model", "EventoFotografia", "Evento", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Digiphoto.Lumen.Model.Evento), "Fotografia", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Digiphoto.Lumen.Model.Fotografia))]
[assembly: EdmRelationshipAttribute("Digiphoto.Lumen.Model", "RigaAlbumFotografia", "RigaAlbum", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Digiphoto.Lumen.Model.RigaAlbum), "Fotografia", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Digiphoto.Lumen.Model.Fotografia))]
[assembly: EdmRelationshipAttribute("Digiphoto.Lumen.Model", "AlbumRigaAlbum", "Album", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Digiphoto.Lumen.Model.Album), "RigaAlbum", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Digiphoto.Lumen.Model.RigaAlbum))]
[assembly: EdmRelationshipAttribute("Digiphoto.Lumen.Model", "FotografoScaricoCard", "Fotografo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Digiphoto.Lumen.Model.Fotografo), "ScaricoCard", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Digiphoto.Lumen.Model.ScaricoCard))]

#endregion

namespace Digiphoto.Lumen.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class LumenEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new LumenEntities object using the connection string found in the 'LumenEntities' section of the application configuration file.
        /// </summary>
        public LumenEntities() : base("name=LumenEntities", "LumenEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LumenEntities object.
        /// </summary>
        public LumenEntities(string connectionString) : base(connectionString, "LumenEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LumenEntities object.
        /// </summary>
        public LumenEntities(EntityConnection connection) : base(connection, "LumenEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Fotografo> Fotografi
        {
            get
            {
                if ((_Fotografi == null))
                {
                    _Fotografi = base.CreateObjectSet<Fotografo>("Fotografi");
                }
                return _Fotografi;
            }
        }
        private ObjectSet<Fotografo> _Fotografi;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Fotografia> Fotografie
        {
            get
            {
                if ((_Fotografie == null))
                {
                    _Fotografie = base.CreateObjectSet<Fotografia>("Fotografie");
                }
                return _Fotografie;
            }
        }
        private ObjectSet<Fotografia> _Fotografie;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Evento> Eventi
        {
            get
            {
                if ((_Eventi == null))
                {
                    _Eventi = base.CreateObjectSet<Evento>("Eventi");
                }
                return _Eventi;
            }
        }
        private ObjectSet<Evento> _Eventi;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Album> Albums
        {
            get
            {
                if ((_Albums == null))
                {
                    _Albums = base.CreateObjectSet<Album>("Albums");
                }
                return _Albums;
            }
        }
        private ObjectSet<Album> _Albums;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RigaAlbum> RigheAlbum
        {
            get
            {
                if ((_RigheAlbum == null))
                {
                    _RigheAlbum = base.CreateObjectSet<RigaAlbum>("RigheAlbum");
                }
                return _RigheAlbum;
            }
        }
        private ObjectSet<RigaAlbum> _RigheAlbum;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ScaricoCard> ScarichiCards
        {
            get
            {
                if ((_ScarichiCards == null))
                {
                    _ScarichiCards = base.CreateObjectSet<ScaricoCard>("ScarichiCards");
                }
                return _ScarichiCards;
            }
        }
        private ObjectSet<ScaricoCard> _ScarichiCards;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FormatoCarta> FormatiCarta
        {
            get
            {
                if ((_FormatiCarta == null))
                {
                    _FormatiCarta = base.CreateObjectSet<FormatoCarta>("FormatiCarta");
                }
                return _FormatiCarta;
            }
        }
        private ObjectSet<FormatoCarta> _FormatiCarta;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Fotografi EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFotografi(Fotografo fotografo)
        {
            base.AddObject("Fotografi", fotografo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Fotografie EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFotografie(Fotografia fotografia)
        {
            base.AddObject("Fotografie", fotografia);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Eventi EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEventi(Evento evento)
        {
            base.AddObject("Eventi", evento);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Albums EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAlbums(Album album)
        {
            base.AddObject("Albums", album);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RigheAlbum EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRigheAlbum(RigaAlbum rigaAlbum)
        {
            base.AddObject("RigheAlbum", rigaAlbum);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ScarichiCards EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToScarichiCards(ScaricoCard scaricoCard)
        {
            base.AddObject("ScarichiCards", scaricoCard);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FormatiCarta EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFormatiCarta(FormatoCarta formatoCarta)
        {
            base.AddObject("FormatiCarta", formatoCarta);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Digiphoto.Lumen.Model", Name="Album")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Album : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Album object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="titolo">Initial value of the titolo property.</param>
        /// <param name="note">Initial value of the note property.</param>
        /// <param name="timestamp">Initial value of the timestamp property.</param>
        public static Album CreateAlbum(global::System.Int32 id, global::System.String titolo, global::System.String note, global::System.DateTime timestamp)
        {
            Album album = new Album();
            album.id = id;
            album.titolo = titolo;
            album.note = note;
            album.timestamp = timestamp;
            return album;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String titolo
        {
            get
            {
                return _titolo;
            }
            set
            {
                OntitoloChanging(value);
                ReportPropertyChanging("titolo");
                _titolo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("titolo");
                OntitoloChanged();
            }
        }
        private global::System.String _titolo;
        partial void OntitoloChanging(global::System.String value);
        partial void OntitoloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String note
        {
            get
            {
                return _note;
            }
            set
            {
                OnnoteChanging(value);
                ReportPropertyChanging("note");
                _note = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("note");
                OnnoteChanged();
            }
        }
        private global::System.String _note;
        partial void OnnoteChanging(global::System.String value);
        partial void OnnoteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime timestamp
        {
            get
            {
                return _timestamp;
            }
            set
            {
                OntimestampChanging(value);
                ReportPropertyChanging("timestamp");
                _timestamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("timestamp");
                OntimestampChanged();
            }
        }
        private global::System.DateTime _timestamp;
        partial void OntimestampChanging(global::System.DateTime value);
        partial void OntimestampChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Digiphoto.Lumen.Model", "AlbumRigaAlbum", "RigaAlbum")]
        public EntityCollection<RigaAlbum> RigaAlbum
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RigaAlbum>("Digiphoto.Lumen.Model.AlbumRigaAlbum", "RigaAlbum");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RigaAlbum>("Digiphoto.Lumen.Model.AlbumRigaAlbum", "RigaAlbum", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Digiphoto.Lumen.Model", Name="Evento")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Evento : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Evento object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="descrizione">Initial value of the descrizione property.</param>
        public static Evento CreateEvento(global::System.Guid id, global::System.String descrizione)
        {
            Evento evento = new Evento();
            evento.id = id;
            evento.descrizione = descrizione;
            return evento;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Guid _id;
        partial void OnidChanging(global::System.Guid value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descrizione
        {
            get
            {
                return _descrizione;
            }
            set
            {
                OndescrizioneChanging(value);
                ReportPropertyChanging("descrizione");
                _descrizione = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descrizione");
                OndescrizioneChanged();
            }
        }
        private global::System.String _descrizione;
        partial void OndescrizioneChanging(global::System.String value);
        partial void OndescrizioneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean attivo
        {
            get
            {
                return _attivo;
            }
            set
            {
                OnattivoChanging(value);
                ReportPropertyChanging("attivo");
                _attivo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("attivo");
                OnattivoChanged();
            }
        }
        private global::System.Boolean _attivo = true;
        partial void OnattivoChanging(global::System.Boolean value);
        partial void OnattivoChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Digiphoto.Lumen.Model", Name="FormatoCarta")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FormatoCarta : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FormatoCarta object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="descrizione">Initial value of the descrizione property.</param>
        /// <param name="prezzo">Initial value of the prezzo property.</param>
        public static FormatoCarta CreateFormatoCarta(global::System.Guid id, global::System.String descrizione, global::System.Decimal prezzo)
        {
            FormatoCarta formatoCarta = new FormatoCarta();
            formatoCarta.id = id;
            formatoCarta.descrizione = descrizione;
            formatoCarta.prezzo = prezzo;
            return formatoCarta;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Guid _id;
        partial void OnidChanging(global::System.Guid value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descrizione
        {
            get
            {
                return _descrizione;
            }
            set
            {
                OndescrizioneChanging(value);
                ReportPropertyChanging("descrizione");
                _descrizione = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descrizione");
                OndescrizioneChanged();
            }
        }
        private global::System.String _descrizione;
        partial void OndescrizioneChanging(global::System.String value);
        partial void OndescrizioneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal prezzo
        {
            get
            {
                return _prezzo;
            }
            set
            {
                OnprezzoChanging(value);
                ReportPropertyChanging("prezzo");
                _prezzo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("prezzo");
                OnprezzoChanged();
            }
        }
        private global::System.Decimal _prezzo;
        partial void OnprezzoChanging(global::System.Decimal value);
        partial void OnprezzoChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Digiphoto.Lumen.Model", Name="Fotografia")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Fotografia : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Fotografia object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="nomeFile">Initial value of the nomeFile property.</param>
        /// <param name="dataOraAcquisizione">Initial value of the dataOraAcquisizione property.</param>
        public static Fotografia CreateFotografia(global::System.Guid id, global::System.String nomeFile, global::System.DateTime dataOraAcquisizione)
        {
            Fotografia fotografia = new Fotografia();
            fotografia.id = id;
            fotografia.nomeFile = nomeFile;
            fotografia.dataOraAcquisizione = dataOraAcquisizione;
            return fotografia;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Guid _id;
        partial void OnidChanging(global::System.Guid value);
        partial void OnidChanged();
    
        /// <summary>
        /// nome del file senza il percorso
        /// </summary>
        /// <LongDescription>
        /// E&apos; il nome originale del file cosi come generato dalla fotocamera
        /// </LongDescription>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nomeFile
        {
            get
            {
                return _nomeFile;
            }
            set
            {
                OnnomeFileChanging(value);
                ReportPropertyChanging("nomeFile");
                _nomeFile = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nomeFile");
                OnnomeFileChanged();
            }
        }
        private global::System.String _nomeFile;
        partial void OnnomeFileChanging(global::System.String value);
        partial void OnnomeFileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dataOraScatto
        {
            get
            {
                return _dataOraScatto;
            }
            set
            {
                OndataOraScattoChanging(value);
                ReportPropertyChanging("dataOraScatto");
                _dataOraScatto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dataOraScatto");
                OndataOraScattoChanged();
            }
        }
        private Nullable<global::System.DateTime> _dataOraScatto;
        partial void OndataOraScattoChanging(Nullable<global::System.DateTime> value);
        partial void OndataOraScattoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String didascalia
        {
            get
            {
                return _didascalia;
            }
            set
            {
                OndidascaliaChanging(value);
                ReportPropertyChanging("didascalia");
                _didascalia = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("didascalia");
                OndidascaliaChanged();
            }
        }
        private global::System.String _didascalia;
        partial void OndidascaliaChanging(global::System.String value);
        partial void OndidascaliaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime dataOraAcquisizione
        {
            get
            {
                return _dataOraAcquisizione;
            }
            set
            {
                OndataOraAcquisizioneChanging(value);
                ReportPropertyChanging("dataOraAcquisizione");
                _dataOraAcquisizione = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dataOraAcquisizione");
                OndataOraAcquisizioneChanged();
            }
        }
        private global::System.DateTime _dataOraAcquisizione;
        partial void OndataOraAcquisizioneChanging(global::System.DateTime value);
        partial void OndataOraAcquisizioneChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Digiphoto.Lumen.Model", "FotografoFotografia", "Fotografo")]
        public Fotografo fotografo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Fotografo>("Digiphoto.Lumen.Model.FotografoFotografia", "Fotografo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Fotografo>("Digiphoto.Lumen.Model.FotografoFotografia", "Fotografo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Fotografo> fotografoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Fotografo>("Digiphoto.Lumen.Model.FotografoFotografia", "Fotografo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Fotografo>("Digiphoto.Lumen.Model.FotografoFotografia", "Fotografo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Digiphoto.Lumen.Model", "EventoFotografia", "Evento")]
        public Evento evento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Evento>("Digiphoto.Lumen.Model.EventoFotografia", "Evento").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Evento>("Digiphoto.Lumen.Model.EventoFotografia", "Evento").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Evento> eventoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Evento>("Digiphoto.Lumen.Model.EventoFotografia", "Evento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Evento>("Digiphoto.Lumen.Model.EventoFotografia", "Evento", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Operatori scattini e fotografi
    /// </summary>
    /// <LongDescription>
    /// Anagrafica dei fotografi che producono foto
    /// </LongDescription>
    [EdmEntityTypeAttribute(NamespaceName="Digiphoto.Lumen.Model", Name="Fotografo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Fotografo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Fotografo object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="cognomeNome">Initial value of the cognomeNome property.</param>
        /// <param name="iniziali">Initial value of the iniziali property.</param>
        public static Fotografo CreateFotografo(global::System.String id, global::System.String cognomeNome, global::System.String iniziali)
        {
            Fotografo fotografo = new Fotografo();
            fotografo.id = id;
            fotografo.cognomeNome = cognomeNome;
            fotografo.iniziali = iniziali;
            return fotografo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// Identificatico univoco del fotografo in tutte le installazioni
        /// </summary>
        /// <LongDescription>
        /// Utilizzare per esempio il codice fiscale
        /// </LongDescription>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.String _id;
        partial void OnidChanging(global::System.String value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cognomeNome
        {
            get
            {
                return _cognomeNome;
            }
            set
            {
                OncognomeNomeChanging(value);
                ReportPropertyChanging("cognomeNome");
                _cognomeNome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("cognomeNome");
                OncognomeNomeChanged();
            }
        }
        private global::System.String _cognomeNome;
        partial void OncognomeNomeChanging(global::System.String value);
        partial void OncognomeNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String iniziali
        {
            get
            {
                return _iniziali;
            }
            set
            {
                OninizialiChanging(value);
                ReportPropertyChanging("iniziali");
                _iniziali = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("iniziali");
                OninizialiChanged();
            }
        }
        private global::System.String _iniziali;
        partial void OninizialiChanging(global::System.String value);
        partial void OninizialiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean attivo
        {
            get
            {
                return _attivo;
            }
            set
            {
                OnattivoChanging(value);
                ReportPropertyChanging("attivo");
                _attivo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("attivo");
                OnattivoChanged();
            }
        }
        private global::System.Boolean _attivo = true;
        partial void OnattivoChanging(global::System.Boolean value);
        partial void OnattivoChanged();
    
        /// <summary>
        /// Umano oppure Automatico (OnRide)
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean umano
        {
            get
            {
                return _umano;
            }
            set
            {
                OnumanoChanging(value);
                ReportPropertyChanging("umano");
                _umano = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("umano");
                OnumanoChanged();
            }
        }
        private global::System.Boolean _umano = true;
        partial void OnumanoChanging(global::System.Boolean value);
        partial void OnumanoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String note
        {
            get
            {
                return _note;
            }
            set
            {
                OnnoteChanging(value);
                ReportPropertyChanging("note");
                _note = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("note");
                OnnoteChanged();
            }
        }
        private global::System.String _note;
        partial void OnnoteChanging(global::System.String value);
        partial void OnnoteChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Digiphoto.Lumen.Model", Name="RigaAlbum")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RigaAlbum : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RigaAlbum object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static RigaAlbum CreateRigaAlbum(global::System.Int32 id)
        {
            RigaAlbum rigaAlbum = new RigaAlbum();
            rigaAlbum.id = id;
            return rigaAlbum;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Digiphoto.Lumen.Model", "RigaAlbumFotografia", "Fotografia")]
        public EntityCollection<Fotografia> Fotografia
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Fotografia>("Digiphoto.Lumen.Model.RigaAlbumFotografia", "Fotografia");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Fotografia>("Digiphoto.Lumen.Model.RigaAlbumFotografia", "Fotografia", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Foto Scattate
    /// </summary>
    /// <LongDescription>
    /// Questa entità rappresenta l&apos;azione di scaricare una memory card nel computer. In pratica sono le foto che un fotografo ha scattato in un periodo
    /// </LongDescription>
    [EdmEntityTypeAttribute(NamespaceName="Digiphoto.Lumen.Model", Name="ScaricoCard")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ScaricoCard : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ScaricoCard object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="tempo">Initial value of the tempo property.</param>
        /// <param name="totFoto">Initial value of the totFoto property.</param>
        public static ScaricoCard CreateScaricoCard(global::System.Guid id, global::System.DateTime tempo, global::System.Int16 totFoto)
        {
            ScaricoCard scaricoCard = new ScaricoCard();
            scaricoCard.id = id;
            scaricoCard.tempo = tempo;
            scaricoCard.totFoto = totFoto;
            return scaricoCard;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Guid _id;
        partial void OnidChanging(global::System.Guid value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime tempo
        {
            get
            {
                return _tempo;
            }
            set
            {
                OntempoChanging(value);
                ReportPropertyChanging("tempo");
                _tempo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tempo");
                OntempoChanged();
            }
        }
        private global::System.DateTime _tempo;
        partial void OntempoChanging(global::System.DateTime value);
        partial void OntempoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 totFoto
        {
            get
            {
                return _totFoto;
            }
            set
            {
                OntotFotoChanging(value);
                ReportPropertyChanging("totFoto");
                _totFoto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("totFoto");
                OntotFotoChanged();
            }
        }
        private global::System.Int16 _totFoto;
        partial void OntotFotoChanging(global::System.Int16 value);
        partial void OntotFotoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Digiphoto.Lumen.Model", "FotografoScaricoCard", "Fotografo")]
        public Fotografo Fotografo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Fotografo>("Digiphoto.Lumen.Model.FotografoScaricoCard", "Fotografo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Fotografo>("Digiphoto.Lumen.Model.FotografoScaricoCard", "Fotografo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Fotografo> FotografoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Fotografo>("Digiphoto.Lumen.Model.FotografoScaricoCard", "Fotografo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Fotografo>("Digiphoto.Lumen.Model.FotografoScaricoCard", "Fotografo", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
