//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace Digiphoto.Lumen.Model
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(FormatoCarta))]
    [KnownType(typeof(Fotografo))]
    [KnownType(typeof(Fotografia))]
    public partial class RiCaFotoStampata : RigaCarrello
    {
        [DataMember]
        public Nullable<short> totFogliStampati { get; set; }
        [DataMember]
        public Nullable<System.Guid> idFotografia { get; set; }
    
        [DataMember]
        public virtual FormatoCarta formatoCarta { get; set; }
        [DataMember]
        public virtual Fotografo fotografo { get; set; }
        [DataMember]
        public virtual Fotografia fotografia { get; set; }
    }
    
}
