//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace Digiphoto.Lumen.Model
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(RiCaFotoStampata))]
    [KnownType(typeof(RiCaDiscoMasterizzato))]
    public partial class RigaCarrello
    {
        [DataMember]
        public System.Guid id { get; set; }
        [DataMember]
        public decimal prezzoLordoUnitario { get; set; }
        [DataMember]
        public short quantita { get; set; }
        [DataMember]
        public decimal prezzoNettoTotale { get; set; }
        [DataMember]
        public Nullable<decimal> sconto { get; set; }
        [DataMember]
        public string descrizione { get; set; }
    }
    
}
