//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Digiphoto.Lumen.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class RigaCarrello : INotifyPropertyChanged 
    {
    	public System.Guid id { get; set; }
    	public decimal prezzoLordoUnitario { get; set; }
    	
    	private short _quantita;
    	public short quantita {
    		get {
    			return _quantita;
    		}
    		set {
    			if( _quantita != value ) {
    				_quantita = value;
    				OnPropertyChanged("quantita");
    			}
    		}
    	}
    
    	
    	private decimal _prezzoNettoTotale;
    	public decimal prezzoNettoTotale {
    		get {
    			return _prezzoNettoTotale;
    		}
    		set {
    			if( _prezzoNettoTotale != value ) {
    				_prezzoNettoTotale = value;
    				OnPropertyChanged("prezzoNettoTotale");
    			}
    		}
    	}
    
    	public Nullable<decimal> sconto { get; set; }
    	public string descrizione { get; set; }
    	public string discriminator { get; set; }
    	public Nullable<short> totFogliStampati { get; set; }
    	public string nomeStampante { get; set; }
    	public Nullable<bool> bordiBianchi { get; set; }
    	public System.Guid carrello_id { get; set; }
    	public string fotografo_id { get; set; }
    	public Nullable<System.Guid> fotografia_id { get; set; }
    	public Nullable<System.Guid> formatoCarta_id { get; set; }
    
        public virtual Carrello carrello { get; set; }
        public virtual FormatoCarta formatoCarta { get; set; }
        public virtual Fotografo fotografo { get; set; }
        public virtual Fotografia fotografia { get; set; }
    
    	#region INotifyPropertyChanged
    	public event PropertyChangedEventHandler PropertyChanged;
    
    	protected void OnPropertyChanged(string propertyName)
    	{
    		OnPropertyChanged(new PropertyChangedEventArgs(propertyName));
    	}
    
    	protected virtual void OnPropertyChanged(PropertyChangedEventArgs e)
    	{
    		if (PropertyChanged != null)
    			PropertyChanged(this, e);
    	}
    	#endregion INotifyPropertyChanged	
    }
}
