//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace Digiphoto.Lumen.Model
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Fotografo))]
    public partial class ScaricoCard
    {
        [DataMember]
        public System.Guid id { get; set; }
        [DataMember]
        public System.DateTime tempo { get; set; }
        [DataMember]
        public short totFoto { get; set; }
    
        [DataMember]
        public virtual Fotografo fotografo { get; set; }
    }
    
}
