//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Digiphoto.Lumen.Model {
	using System;
	using System.Collections.Generic;
	using System.ComponentModel;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;

	[Table( "IncassiFotografi" )]
	public partial class IncassoFotografo : INotifyPropertyChanged {

		#region Attributi

		[Key]
		public System.Guid id { get; set; }

		public decimal incasso { get; set; }
		
		public decimal incassoStampe { get; set; }
		
		public decimal incassoMasterizzate { get; set; }
		
		public short contaStampe { get; set; }
		
		public short contaMasterizzate { get; set; }
		
		public Nullable<decimal> provvigioni { get; set; }
		
		[Required]
		[ForeignKey("fotografo")]		
		public string fotografo_id { get; set; }
		public virtual Fotografo fotografo { get; set; }

		[Required]
		[ForeignKey( "carrello" )]
		public System.Guid carrello_id { get; set; }
		public virtual Carrello carrello { get; set; }
		

		#endregion Attributi

		#region INotifyPropertyChanged
		public event PropertyChangedEventHandler PropertyChanged;

		protected void OnPropertyChanged( string propertyName ) {
			OnPropertyChanged( new PropertyChangedEventArgs( propertyName ) );
		}

		protected virtual void OnPropertyChanged( PropertyChangedEventArgs e ) {
			if( PropertyChanged != null )
				PropertyChanged( this, e );
		}
		#endregion INotifyPropertyChanged	
	}
}
